/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head';
import rocketDab from '../public/img/rocketdab.png';
import explorer from '../public/img/rocketride.png';
import Image from 'next/image';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Acme Rockets</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<header className='top sticky z-10 bg-teal-700 text-white'>
				<section className='max-width-4xl mx-auto flex items-center justify-between p-4 sm:justify-around'>
					<h1 className='text-3xl font-medium'>
						<a href='#hero'>🚀 Acme Rockets</a>
					</h1>
					<>
						<button
							id='mobile-open-button'
							className='text-3xl focus:outline-none sm:hidden'
						>
							&#9776;
						</button>
						<nav
							className='hidden space-x-8 text-xl sm:block'
							aria-label='main'
						>
							<a href='#rockets' className='hover:opacity-90'>
								Our Rockets
							</a>
							<a href='#testimonials' className='hover:opacity-90'>
								Testimonials
							</a>
							<a href='#contact' className='hover:opacity-90'>
								Contact Us
							</a>
						</nav>
					</>
				</section>
			</header>

			<main className='mx-auto max-w-4xl'>
				<section
					id='hero'
					className='mb-12 flex flex-col-reverse items-center justify-center gap-8 p-6 sm:flex-row'
				>
					<article className='sm:w-1/2'>
						<h2 className='max-w-md text-center text-4xl font-bold text-slate-900 dark:text-white sm:text-left sm:text-5xl'>
							We boldly go
							<span className='text-indigo-700 dark:text-indigo-300'>
								{' '}
								where no rocket
							</span>{' '}
							has gone before
						</h2>
						<p className='mt-4 max-w-md text-center text-2xl text-slate-700 dark:text-slate-400 sm:text-left'>
							We're building rockets for the next century today. From the moon
							to mars, jupiter and beyond
						</p>
						<p className='mt-4 max-w-md text-center text-2xl text-slate-700 dark:text-slate-400 sm:text-left'>
							Think Acme Rockets
						</p>
					</article>
					<Image src={rocketDab} alt='rocket man' className='w-1/2' />
				</section>
				<hr className='mx-auto w-1/2 bg-black dark:bg-white' />
				<section id='rockets' className='my-12 p-6'>
					<h2 className='mb-6 text-center text-4xl font-bold text-slate-900 dark:text-white sm:text-5xl'>
						Our Rockets
					</h2>
					<ul className='mx-auto my-12 flex list-none flex-col items-center gap-8 sm:flex-row'>
						<li className='flex w-2/3 flex-col items-center rounded-3xl border border-solid border-slate-900 bg-white py-6 px-2 shadow-xl dark:border-gray-100 dark:bg-black sm:w-5/6'>
							<Image src={explorer} alt='Explorer' className='mb-6 w-1/2' />
							<h3 className='text-center text-3xl text-slate-900 dark:text-white'>
								Explorer
							</h3>
							<p className='mt-2 hidden text-center text-3xl text-slate-500 dark:text-slate-400 sm:block'>
								$
							</p>
							<p className='mt-2 text-center text-2xl text-slate-500 dark:text-slate-400 sm:hidden'>
								Affordable Exploration
							</p>
						</li>
					</ul>
				</section>
				<hr className='mx-auto w-1/2 bg-black dark:bg-white' />
				<section id='testimonials' className='my-12 p-6'>
					<h2 className='mb-6 text-center text-4xl font-bold text-slate-900 dark:text-white sm:text-5xl'>
						Testimonials
					</h2>
				</section>
				<hr className='mx-auto w-1/2 bg-black dark:bg-white' />
				<section id='contact' className='my-12 p-6'>
					<h2 className='mb-6 text-center text-4xl font-bold text-slate-900 dark:text-white sm:text-5xl'>
						Contact Us
					</h2>
				</section>
			</main>
		</div>
	);
}
